# Activity 01 - Instructor Turn - Mongodb Basics - üë©‚Äçüè´üßë‚Äçüè´ 

### Query 1 - Creating dbs, inserting data and finding data

* Start up a new database by switching to it. The db does not exist until you create a collection.

  ```shell
  use travel_db
  ```

* Show the current db by running db.

  ```
  db
  ```

* Show current databases in existence

  ```
  show dbs
  ```

* Create a collection

  ```shell
  db.createCollection("destinations")
  ```

* See all collections in a database

  ```bash
  show collections
  ```

* Insert data into the travel_db database with this command.

  - NOTE: This will also create the collection automatically, the contents of the insert are basically a JavaScript object, and include an array.

```shell
db.destinations.insertOne({"continent": "Africa", "country": "Morocco","major_cities": ["Casablanca", "Fez", "Marrakech"]})
```

* Add 3-5 more countries and insert them into the db using the same syntax as above.

```shell
db.destinations.insertOne({"continent": "Europe", "country": "France", "major_cities": ["Paris", "Marseille", "Bordeaux"]})

db.destinations.insertOne({"continent": "North America", "country": "USA", "major_cities": ["Washington DC", "New York City", "San Francisco"]})
```

* Observe where the data was entered in the MongoDB instance (in mongod)

* Find all data in a Collection with `db.[COLLECTION_NAME].find()`

  - The MongoDB \_id was created automatically.

  - This id is specific for each doc in the collection.

```shell
db.destinations.find()
```

* Find specific data by matching a field.

```shell
db.destinations.find({"continent": "Africa"})
db.destinations.find({"country": "Morocco"})
```

* Try a few queries with the examples we came up with as a class.

  - Also, pick something that will find more than one entry so we can see how it will return all matches.

  - Find specific data by matching an \_id.

```shell
db.destinations.find({_id: ObjectId("<ID Number Here>")})
db.destinations.find({_id: ObjectId("5416fe1d94bcf86cd785439036")})
```

# Activity 02 - Student Turn - Mongo Class - üë©‚Äçüéìüë®‚Äçüéì 

In this activity, you will learn basic query operations in MongoDB. Specifically, you'll practice inserting and finding documents.

## Instructions

1. Use the command line to create a `classDB` database.

2. Insert entries into this database for yourself and other students within a collection called `classroom`. Each document should have:
  * A name field for the person's `name`
  * A `favorite_python_library` field for the person's favorite Python library
  * An `age` field for the person's age
  * A `hobbies` field for a list of that person's hobbies.

3. Use the `find()` commands to get a list of everyone of a specific age, then use `name` to collect the entry for a single person.

---

In [ ]:
# MUST DO THIS ACTIVITY IN THE ANACONDA PROMPT OR TERMINAL

<details>
  <summary><strong>‚úÖ Solution 02 Click HERE</strong></summary>


## A. Use the command line to create a classDB database.

* Insert entries for  yourself and other students within a collection called `classroom`. Each document should have:

1. A field of name with the person's name.
2. A field of the person's favorite Python library, e.g. pandas.
3. A field of a list of the person's hobbies .

## Example:

```python
use classDB

db.classroom.insertOne({name: 'Mariah', age: 23, favorite_python_library: 'Seaborn', hobbies: ['Coding', 'Reading', 'Running']})

db.classroom.insertOne({name: 'Ricky', age: 34, favorite_python_library: 'Matplotlib', hobbies: ['Not Coding', 'Not Reading', 'Not Running', 'Guitar']})

db.classroom.insertOne({name: 'Srikanth', age: 28, favorite_python_library: 'Pandas', hobbies: ['Netflix', 'Guitar', 'Traveling']})
```

## B. Use find commands to get:

1. A list of everyone of a certain age.


```python
db.classroom.find({age: 23})
```

2. An entry for a single person.


```python
db.classroom.find({name: 'Ricky'})
```

</details>

# Activity 03 - Instructor Turn - Update, Delete and Drop in MongoDB - üë©‚Äçüè´üßë‚Äçüè´

* Use the travel_db

    ```shell
    db
    use travel_db
    ```

* Insert two countries in Africa

```shell
db.destinations.insertOne({'country': 'Egypt', 'continent': 'Africa', major_cities: ['Cairo', 'Luxor']})

db.destinations.insertOne({'country': 'Nigeria', 'continent': 'Africa', major_cities: ['Lagos', 'Kano']})
```

* How to update data using `db.[COLLECTION_NAME].updateOne()`

```shell
db.destinations.updateOne({"country": "Egypt"}, {$set: {"continent": "Antarctica"}})
```

    * Note that the above will only update the first entry it matches.

* To update multiple entries, use the `updateMany()` method. The following will update all countries listed as being in Africa to now show Antarctica as their continent

    ```shell
    db.destinations.updateMany({"continent": "Africa"}, {$set: {"continent": "Antarctica"}})
    ```

* What will happen when you run this command, even though a capital doesn't exist.

    ```shell
    db.destinations.updateOne({"country": "Morocco"}, {$set: {"capital": "Rabat"}})
    ```

* Answer: it will add the capital field to the document and show the field can now be updated with the same command.

    ```shell
    db.destinations.updateOne({"country": "Morocco"}, {$set: {"capital": "RABAT"}})
    ```

* Show how to push to an array with `$push`.

    ```shell
    db.destinations.updateOne({"country": "Morocco"}, {$push: {"major_cities": "Agadir"}})
    ```

* The upsert option updates a document if one exists; it otherwise creates a new document.

    ```shell
    db.destinations.updateOne({'country': 'Canada'}, {$set: {'capital': 'Ottawa'}}, {upsert: true})
    ```

* Delete an entry with `db.[COLLECTION_NAME].deleteOne()`.

    ```shell
    db.destinations.deleteOne({"country": "Morocco"})
    ```

* Empty a collection with `db.[COLLECTION_NAME].deleteMany()`.

    ```shell
    db.destinations.deleteMany({})
    ```

* Drop a collection with `db.[COLLECTION_NAME].drop()`.

    ```shell
    db.destinations.drop()
    ```

* Drop a database

    ```shell
    db.dropDatabase()
    ```

# Activity 04 - Student Turn - Create a GardenDB - üë©‚Äçüéìüë®‚Äçüéì 

In this activity, you will gain further practice with CRUD operations in MongoDB by creating a database centered around gardening.

## Instructions

* Create a new database called `gardenDB` using the mongo shell.

* Create a collection called `plants` that contains the following:
  * A string field for `plantName`
  * An integer field for `yearsGrowing`
  * A Boolean field for `stillAlive`
  * An array of strings called `PlantNutrition` to store information about how best to keep the plant alive

* Insert three new documents into the collection. You can be creative with what you put in here and have some fun with it. Getting some practice using the commands is more important than accuracy of information.

* Update the `yearsGrowing` fields for your documents so that they are one greater than their original values.

* Update the `stillAlive` value for one of the documents so that it is now `false`.

* Add a new value into the `plantNutrition` array for one of the documents.

* Find the plant in the collection that isn't alive and delete it from the collection.

* Drop the `plants` collection.

* Delete the `gardenDB` database

---

In [3]:
# MUST DO THIS ACTIVITY IN THE 
# ANACONDA PROMPT for windows OR 
# TERMINAL for macs

<details>
  <summary><strong>‚úÖ Solution 04 Click HERE</strong></summary>

# Create a Garden Database

* Create a new database called `gardenDB` using the mongo shell.

    ```
    use gardenDB
    ```

* Create a collection called `plants` with a string field for `plantName`, an integer field for `yearsGrowing`, a boolean field for `stillAlive`, and an array of strings for `plantNutrition`.


* Insert three new documents into the collection. Be creative and have some fun with the documents that you add.

    ```shell
    db.plants.insertOne({"plantName":"Fuschia", "yearsGrowing":10, "stillAlive": true, "plantNutrition":["nitrogen", "sulfur", "calcium", "potassium"]})

    db.plants.insertOne({"plantName":"Watermelon", "yearsGrowing":2, "stillAlive": true, "plantNutrition":["nitrogen based fertilizer at onset", "phosphorus and potassium fertilizer when flowering"]})

    db.plants.insertOne({"plantName":"Avocado", "yearsGrowing":12, "stillAlive": true, "plantNutrition":["nitrogen", "zinc"]})
    ```

* Update the `yearsGrowing` fields for your documents so that they are one greater than their original values.

    ```shell
    db.plants.updateOne({"plantName":"Fuschia"},{$set:{"yearsGrowing":11}})
    db.plants.updateOne({"plantName":"Watermelon"},{$set:{"yearsGrowing":3}})
    db.plants.updateOne({"plantName":"Avocado"},{$set:{"yearsGrowing":13}})
    ```

* We can actually also use `updateMany()` to update all documents at once if we want to update them the same way. The following will have the same effect as updating each document individually as we did above:

    ```shell
    db.plants.updateMany({},{$inc: {"yearsGrowing": 1}})
    ```

    [MongoDB documentation on `$inc`](https://www.mongodb.com/docs/manual/reference/operator/update/inc/)

* Update the `stillAlive` value for one of the documents so that it is now `false`.

    ```shell
    db.plants.update({"plantName":"Fuschia"},{$set:{"stillAlive": false}})
    ```

* Add a new value into the `plantNutrition` array for one of the documents.

    ```shell
    db.plants.update({"plantName":"Watermelon"},{$push:{"plantNutrition":"1-2in water per week"}})
    ```

* Find the plant in the collection that isn't alive and remove it from the collection.

    ```shell
    db.plants.deleteOne({"stillAlive":false})
    ```

* Drop the `plants` collection

    ```shell
    db.plants.drop()
    ```

* Delete the `gardenDB` database

    ```shell
    db.dropDatabase()
    ```
</details>

# Activity 05 - Instructor Turn - Import Data - üë©‚Äçüè´üßë‚Äçüè´

* Open Terminal and navigate to the resources folder where mechanics.json and customers.csv are stored.

* Import the `mechanics.json` file with the following line in Terminal:

    ```shell
    mongoimport --type json -d autosaurus -c mechanics --drop --jsonArray mechanics.json
    ```

* Import the `customers.csv` file with the following line in Terminal:

    ```shell
    mongoimport --type csv -d autosaurus -c customers --headerline --drop customers.csv
    ```

* Check the contents of the data in Mongo Shell.

* Run `mongo` from the Terminal to launch Mongo.

* Switch to the `autosaurus` database we created with the previous imports:

    ```shell
    use autosaurus
    ```

* Display the list of collections in the database:

    ```shell
    show collections
    ```

* Find one entry in the customers collection:

    ```shell
    db.customers.findOne()
    ```

* Find the documents in the customers collection where the customer has an Acura for their `car_make`:

    ```shell
    db.customers.find({"car_make": "Acura"})
    ```

* Display the mechanics collection using pretty print:

    ```shell
    db.mechanics.find()
    ```

* Find the mechanic in the mechanics collection that specialises in Acuras:

    ```shell
    db.mechanics.find({"car_specialties": "Acura"})
    ```

* Display the mechanics who work 40 hour weeks:

    ```shell
    db.mechanics.find({"wages.weekly_hours": 40})
    ```

* Convert string field `wages.hourly_rate` to a floating point value or "double":

    ```shell
    db.mechanics.updateMany({}, [ {'$set':{ "wages.hourly_rate" : {'$toDouble': "$wages.hourly_rate"}}} ])
    ```


## References 

* Data generated by Mockaroo, LLC. (2022) Realistic Data Generator. [https://www.mockaroo.com/](https://mockaroo.com/).

* Data for this dataset was generated by edX Boot Camps LLC, and is intended for educational purposes only.

# Activity 06 - Student Turn - Import, Update, and Explore - üë©‚Äçüéìüë®‚Äçüéì 

In this activity, you will practice importing data from your Terminal, updating data types, and exploring data in the Mongo Shell.

## Instructions

* Write a command that imports the data from [annual_aqi_by_county_2022.csv](resources/annual_aqi_by_county_2022.csv) to a database called `epa` and a collection called `annual_aqi_by_county`. If the collection already exists, drop the collection.

* Write a command that imports the data from [ohio_daily_records_2022.json](resources/ohio_daily_records_2022.json) to a database called `epa` and a collection called `ohio_daily_records`. If the collection already exists, drop the collection.

* Write a command that imports the data from [ohio_jan_2022.json](resources/ohio_jan_2022.json) to a database called `epa` and a collection called `ohio_air`. If the collection already exists, drop the collection.

* Write a command that imports the data from [ohio_feb_2022.json](resources/ohio_feb_2022.json) to a database called `epa` and a collection called `ohio_air`. **Note:** This is the same collection used in the previous import so be sure not to drop the collection in advance.

* Run `mongo` or `mongosh` from your Terminal and verify that your files imported correctly by writing commands to do the following:

  * Use the `epa` database.

  * Show all the collections in the `epa` database.

  * Verify that there is data in each of the 3 collections (`ohio_daily_records`, `annual_aqi_by_county`, and `ohio_air`) by using `findOne()` to display an entry.

  * Verify that there is data from January 2022 in the `ohio_air` collection by searching on the `date_local` field.

  * Verify that there is data from February 2022 in the `ohio_air` collection by searching on the `date_local` field.

* Update the `DAILY_AQI_VALUE` nested under `CO` in the `ohio_daily_records` collection to change the string values to integers.

* Update the `PERCENT_COMPLETE` nested under `CO` in the `ohio_daily_records` collection to change the string values to doubles.

* Find a record in the `ohio_daily_records` collection where `CO.UNITS` matches "ppm" and `NO2.UNITS` matches "ppb". This will help us find sites that recorded values for carbon monoxide and nitrogen dioxide.

## Hints

* Dates for the `ohio_air` collection use the YYYY-MM-DD format.

* Nested records use dot notation.

* Remember to use square brackets as part of your query when changing the data type of a field. Your `updateMany()` query should use the following convention: `updateMany({}, [ {'$set': "field_name": {'$toDataType': "$field_name"}} ])`.

## References

`ohio_daily_records_2022.json`: United States Environmental Protection Agency. 2022. *Download daily data*. Settings: Year "2022", Geographic Area "Ohio", and Pollutants "CO", "NO2", and "SO2". Available: https://www.epa.gov/outdoor-air-quality-data/download-daily-data [2022, October 14].

`annual_aqi_by_county_2022.csv`: United States Environmental Protection Agency. 2022. *Pre-generated data files*. Annual AQI by county 2022. Available: https://aqs.epa.gov/aqsweb/airdata/download_files.html [2022, October 6]. 

`ohio_jan_2022.json` and `ohio_feb_2022.json`: United States Environmental Protection Agency. 2022. *Air Quality System (AQS) API*. Available: https://aqs.epa.gov/aqsweb/documents/data_api.html [2022, October 6]. 

---

<details>
  <summary><strong>‚úÖ Solution 06 Click HERE</strong></summary>
# Import, Update, and Explore

* Write a command that imports the data from [annual_aqi_by_county_2022.csv](../Resources/annual_aqi_by_county_2022.csv) to a database called `epa` and a collection called `annual_aqi_by_county`. If the collection already exists, drop the collection.

    ```shell
    mongoimport --type csv -d epa -c annual_aqi_by_county --headerline --drop annual_aqi_by_county_2022.csv
    ```

* Write a command that imports the data from [ohio_daily_records_2022.json](../Resources/ohio_daily_records_2022.json) to a database called `epa` and a collection called `ohio_daily_records`. If the collection already exists, drop the collection.

    ```shell
    mongoimport --type json -d epa -c ohio_daily_records --drop --jsonArray ohio_daily_records_2022.json
    ```

* Write a command that imports the data from [ohio_jan_2022.json](../Resources/ohio_jan_2022.json) to a database called `epa` and a collection called `ohio_air`. If the collection already exists, drop the collection.

    ```shell
    mongoimport --type json -d epa -c ohio_air --drop --jsonArray ohio_jan_2022.json
    ```

* Write a command that imports the data from [ohio_feb_2022.json](../Resources/ohio_feb_2022.json) to a database called `epa` and a collection called `ohio_air`. **Note:** This is the same collection used in the previous import so be sure not to drop the collection in advance.

    ```shell
    mongoimport --type json -d epa -c ohio_air --jsonArray ohio_feb_2022.json
    ```

* Use the `epa` database.

    ```shell
    use epa
    ```

* Show all the collections in the `epa` database.

    ```shell
    show collections
    ```

    This should display the following output:

    ```text
    annual_aqi_by_county
    ohio_air
    ohio_daily_records
    ```

* Verify that there is data in each of the 3 collections (`ohio_daily_records`, `annual_aqi_by_county`, and `ohio_air`) by using `findOne()` to display an entry.

    ```shell
    db.ohio_daily_records.findOne()
    db.annual_aqi_by_county.findOne()
    db.ohio_air.findOne()
    ```

* Verify that there is data from January 2022 in the `ohio_air` collection by seaching on the `date_local` field.

    ```shell
    db.ohio_air.findOne({"date_local": "2022-01-01"})
    ```

* Verify that there is data from February 2022 in the `ohio_air` collection by seaching on the `date_local` field.

    ```shell
    db.ohio_air.findOne({"date_local": "2022-02-01"})
    ```

* Update the `DAILY_AQI_VALUE` nested under `CO` in the `ohio_daily_records` collection to change the string values to integers.

    ```shell
    db.ohio_daily_records.updateMany({}, [ {'$set':{ "CO.DAILY_AQI_VALUE" : {'$toInt': "$CO.DAILY_AQI_VALUE"}}} ])
    ```

* Update the `PERCENT_COMPLETE` nested under `CO` in the `ohio_daily_records` collection to change the string values to doubles.

    ```shell
    db.ohio_daily_records.updateMany({}, [ {'$set':{ "CO.PERCENT_COMPLETE" : {'$toDouble': "$CO.PERCENT_COMPLETE"}}} ])
    ```

* Find a record in the `ohio_daily_records` collection where `CO.UNITS` matches "ppm" and `NO2.UNITS` matches "ppb"

    ```shell
    db.ohio_daily_records.findOne({"CO.UNITS": "ppm","NO2.UNITS": "ppb"})
    ```

    

</details>